/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Itofinity.Appveyor.Rest.Refit.Api;
using Itofinity.Appveyor.Rest.Refit.Model;
using Itofinity.Appveyor.Rest.Refit.Client;
using System.Reflection;

namespace Itofinity.Appveyor.Rest.Refit.Test
{
    /// <summary>
    ///  Class for testing ProjectConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for ProjectConfiguration
        //private ProjectConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectConfiguration
            //instance = new ProjectConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectConfiguration
        /// </summary>
        [Test]
        public void ProjectConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProjectConfiguration
            //Assert.IsInstanceOfType<ProjectConfiguration> (instance, "variable 'instance' is a ProjectConfiguration");
        }

        /// <summary>
        /// Test the property 'DoNotIncrementBuildNumberOnPullRequests'
        /// </summary>
        [Test]
        public void DoNotIncrementBuildNumberOnPullRequestsTest()
        {
            // TODO unit test for the property 'DoNotIncrementBuildNumberOnPullRequests'
        }
        /// <summary>
        /// Test the property 'HotFixScripts'
        /// </summary>
        [Test]
        public void HotFixScriptsTest()
        {
            // TODO unit test for the property 'HotFixScripts'
        }
        /// <summary>
        /// Test the property 'InitScripts'
        /// </summary>
        [Test]
        public void InitScriptsTest()
        {
            // TODO unit test for the property 'InitScripts'
        }
        /// <summary>
        /// Test the property 'BranchesMode'
        /// </summary>
        [Test]
        public void BranchesModeTest()
        {
            // TODO unit test for the property 'BranchesMode'
        }
        /// <summary>
        /// Test the property 'IncludeBranches'
        /// </summary>
        [Test]
        public void IncludeBranchesTest()
        {
            // TODO unit test for the property 'IncludeBranches'
        }
        /// <summary>
        /// Test the property 'ExcludeBranches'
        /// </summary>
        [Test]
        public void ExcludeBranchesTest()
        {
            // TODO unit test for the property 'ExcludeBranches'
        }
        /// <summary>
        /// Test the property 'SkipTags'
        /// </summary>
        [Test]
        public void SkipTagsTest()
        {
            // TODO unit test for the property 'SkipTags'
        }
        /// <summary>
        /// Test the property 'SkipNonTags'
        /// </summary>
        [Test]
        public void SkipNonTagsTest()
        {
            // TODO unit test for the property 'SkipNonTags'
        }
        /// <summary>
        /// Test the property 'SkipBranchWithPullRequests'
        /// </summary>
        [Test]
        public void SkipBranchWithPullRequestsTest()
        {
            // TODO unit test for the property 'SkipBranchWithPullRequests'
        }
        /// <summary>
        /// Test the property 'SkipCommitsFiles'
        /// </summary>
        [Test]
        public void SkipCommitsFilesTest()
        {
            // TODO unit test for the property 'SkipCommitsFiles'
        }
        /// <summary>
        /// Test the property 'OnlyCommitsFiles'
        /// </summary>
        [Test]
        public void OnlyCommitsFilesTest()
        {
            // TODO unit test for the property 'OnlyCommitsFiles'
        }
        /// <summary>
        /// Test the property 'CloneScripts'
        /// </summary>
        [Test]
        public void CloneScriptsTest()
        {
            // TODO unit test for the property 'CloneScripts'
        }
        /// <summary>
        /// Test the property 'OnBuildSuccessScripts'
        /// </summary>
        [Test]
        public void OnBuildSuccessScriptsTest()
        {
            // TODO unit test for the property 'OnBuildSuccessScripts'
        }
        /// <summary>
        /// Test the property 'OnBuildErrorScripts'
        /// </summary>
        [Test]
        public void OnBuildErrorScriptsTest()
        {
            // TODO unit test for the property 'OnBuildErrorScripts'
        }
        /// <summary>
        /// Test the property 'OnBuildFinishScripts'
        /// </summary>
        [Test]
        public void OnBuildFinishScriptsTest()
        {
            // TODO unit test for the property 'OnBuildFinishScripts'
        }
        /// <summary>
        /// Test the property 'PatchAssemblyInfo'
        /// </summary>
        [Test]
        public void PatchAssemblyInfoTest()
        {
            // TODO unit test for the property 'PatchAssemblyInfo'
        }
        /// <summary>
        /// Test the property 'AssemblyInfoFile'
        /// </summary>
        [Test]
        public void AssemblyInfoFileTest()
        {
            // TODO unit test for the property 'AssemblyInfoFile'
        }
        /// <summary>
        /// Test the property 'AssemblyVersionFormat'
        /// </summary>
        [Test]
        public void AssemblyVersionFormatTest()
        {
            // TODO unit test for the property 'AssemblyVersionFormat'
        }
        /// <summary>
        /// Test the property 'AssemblyFileVersionFormat'
        /// </summary>
        [Test]
        public void AssemblyFileVersionFormatTest()
        {
            // TODO unit test for the property 'AssemblyFileVersionFormat'
        }
        /// <summary>
        /// Test the property 'AssemblyInformationalVersionFormat'
        /// </summary>
        [Test]
        public void AssemblyInformationalVersionFormatTest()
        {
            // TODO unit test for the property 'AssemblyInformationalVersionFormat'
        }
        /// <summary>
        /// Test the property 'PatchDotnetCsproj'
        /// </summary>
        [Test]
        public void PatchDotnetCsprojTest()
        {
            // TODO unit test for the property 'PatchDotnetCsproj'
        }
        /// <summary>
        /// Test the property 'DotnetCsprojFile'
        /// </summary>
        [Test]
        public void DotnetCsprojFileTest()
        {
            // TODO unit test for the property 'DotnetCsprojFile'
        }
        /// <summary>
        /// Test the property 'DotnetCsprojVersionFormat'
        /// </summary>
        [Test]
        public void DotnetCsprojVersionFormatTest()
        {
            // TODO unit test for the property 'DotnetCsprojVersionFormat'
        }
        /// <summary>
        /// Test the property 'DotnetCsprojPackageVersionFormat'
        /// </summary>
        [Test]
        public void DotnetCsprojPackageVersionFormatTest()
        {
            // TODO unit test for the property 'DotnetCsprojPackageVersionFormat'
        }
        /// <summary>
        /// Test the property 'MaxJobs'
        /// </summary>
        [Test]
        public void MaxJobsTest()
        {
            // TODO unit test for the property 'MaxJobs'
        }
        /// <summary>
        /// Test the property 'BuildCloud'
        /// </summary>
        [Test]
        public void BuildCloudTest()
        {
            // TODO unit test for the property 'BuildCloud'
        }
        /// <summary>
        /// Test the property 'OperatingSystem'
        /// </summary>
        [Test]
        public void OperatingSystemTest()
        {
            // TODO unit test for the property 'OperatingSystem'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
        /// <summary>
        /// Test the property 'CloneFolder'
        /// </summary>
        [Test]
        public void CloneFolderTest()
        {
            // TODO unit test for the property 'CloneFolder'
        }
        /// <summary>
        /// Test the property 'ShallowClone'
        /// </summary>
        [Test]
        public void ShallowCloneTest()
        {
            // TODO unit test for the property 'ShallowClone'
        }
        /// <summary>
        /// Test the property 'ForceHttpsClone'
        /// </summary>
        [Test]
        public void ForceHttpsCloneTest()
        {
            // TODO unit test for the property 'ForceHttpsClone'
        }
        /// <summary>
        /// Test the property 'CloneDepth'
        /// </summary>
        [Test]
        public void CloneDepthTest()
        {
            // TODO unit test for the property 'CloneDepth'
        }
        /// <summary>
        /// Test the property 'EnvironmentVariables'
        /// </summary>
        [Test]
        public void EnvironmentVariablesTest()
        {
            // TODO unit test for the property 'EnvironmentVariables'
        }
        /// <summary>
        /// Test the property 'EnvironmentVariablesMatrix'
        /// </summary>
        [Test]
        public void EnvironmentVariablesMatrixTest()
        {
            // TODO unit test for the property 'EnvironmentVariablesMatrix'
        }
        /// <summary>
        /// Test the property 'InstallScripts'
        /// </summary>
        [Test]
        public void InstallScriptsTest()
        {
            // TODO unit test for the property 'InstallScripts'
        }
        /// <summary>
        /// Test the property 'HostsEntries'
        /// </summary>
        [Test]
        public void HostsEntriesTest()
        {
            // TODO unit test for the property 'HostsEntries'
        }
        /// <summary>
        /// Test the property 'CacheEntries'
        /// </summary>
        [Test]
        public void CacheEntriesTest()
        {
            // TODO unit test for the property 'CacheEntries'
        }
        /// <summary>
        /// Test the property 'ConfigureNuGetProjectSource'
        /// </summary>
        [Test]
        public void ConfigureNuGetProjectSourceTest()
        {
            // TODO unit test for the property 'ConfigureNuGetProjectSource'
        }
        /// <summary>
        /// Test the property 'ConfigureNuGetAccountSource'
        /// </summary>
        [Test]
        public void ConfigureNuGetAccountSourceTest()
        {
            // TODO unit test for the property 'ConfigureNuGetAccountSource'
        }
        /// <summary>
        /// Test the property 'DisableNuGetPublishOnPullRequests'
        /// </summary>
        [Test]
        public void DisableNuGetPublishOnPullRequestsTest()
        {
            // TODO unit test for the property 'DisableNuGetPublishOnPullRequests'
        }
        /// <summary>
        /// Test the property 'BuildMode'
        /// </summary>
        [Test]
        public void BuildModeTest()
        {
            // TODO unit test for the property 'BuildMode'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Test]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'Configuration'
        /// </summary>
        [Test]
        public void ConfigurationTest()
        {
            // TODO unit test for the property 'Configuration'
        }
        /// <summary>
        /// Test the property 'MsBuildProjectFileName'
        /// </summary>
        [Test]
        public void MsBuildProjectFileNameTest()
        {
            // TODO unit test for the property 'MsBuildProjectFileName'
        }
        /// <summary>
        /// Test the property 'PackageWebApplicationProjects'
        /// </summary>
        [Test]
        public void PackageWebApplicationProjectsTest()
        {
            // TODO unit test for the property 'PackageWebApplicationProjects'
        }
        /// <summary>
        /// Test the property 'PackageWebApplicationProjectsXCopy'
        /// </summary>
        [Test]
        public void PackageWebApplicationProjectsXCopyTest()
        {
            // TODO unit test for the property 'PackageWebApplicationProjectsXCopy'
        }
        /// <summary>
        /// Test the property 'PackageAzureCloudServiceProjects'
        /// </summary>
        [Test]
        public void PackageAzureCloudServiceProjectsTest()
        {
            // TODO unit test for the property 'PackageAzureCloudServiceProjects'
        }
        /// <summary>
        /// Test the property 'PackageNuGetProjects'
        /// </summary>
        [Test]
        public void PackageNuGetProjectsTest()
        {
            // TODO unit test for the property 'PackageNuGetProjects'
        }
        /// <summary>
        /// Test the property 'PackageNuGetSymbols'
        /// </summary>
        [Test]
        public void PackageNuGetSymbolsTest()
        {
            // TODO unit test for the property 'PackageNuGetSymbols'
        }
        /// <summary>
        /// Test the property 'IncludeNuGetReferences'
        /// </summary>
        [Test]
        public void IncludeNuGetReferencesTest()
        {
            // TODO unit test for the property 'IncludeNuGetReferences'
        }
        /// <summary>
        /// Test the property 'MsBuildInParallel'
        /// </summary>
        [Test]
        public void MsBuildInParallelTest()
        {
            // TODO unit test for the property 'MsBuildInParallel'
        }
        /// <summary>
        /// Test the property 'MsBuildVerbosity'
        /// </summary>
        [Test]
        public void MsBuildVerbosityTest()
        {
            // TODO unit test for the property 'MsBuildVerbosity'
        }
        /// <summary>
        /// Test the property 'BuildScripts'
        /// </summary>
        [Test]
        public void BuildScriptsTest()
        {
            // TODO unit test for the property 'BuildScripts'
        }
        /// <summary>
        /// Test the property 'BeforeBuildScripts'
        /// </summary>
        [Test]
        public void BeforeBuildScriptsTest()
        {
            // TODO unit test for the property 'BeforeBuildScripts'
        }
        /// <summary>
        /// Test the property 'BeforePackageScripts'
        /// </summary>
        [Test]
        public void BeforePackageScriptsTest()
        {
            // TODO unit test for the property 'BeforePackageScripts'
        }
        /// <summary>
        /// Test the property 'AfterBuildScripts'
        /// </summary>
        [Test]
        public void AfterBuildScriptsTest()
        {
            // TODO unit test for the property 'AfterBuildScripts'
        }
        /// <summary>
        /// Test the property 'TestMode'
        /// </summary>
        [Test]
        public void TestModeTest()
        {
            // TODO unit test for the property 'TestMode'
        }
        /// <summary>
        /// Test the property 'TestAssemblies'
        /// </summary>
        [Test]
        public void TestAssembliesTest()
        {
            // TODO unit test for the property 'TestAssemblies'
        }
        /// <summary>
        /// Test the property 'TestCategoriesMode'
        /// </summary>
        [Test]
        public void TestCategoriesModeTest()
        {
            // TODO unit test for the property 'TestCategoriesMode'
        }
        /// <summary>
        /// Test the property 'TestCategories'
        /// </summary>
        [Test]
        public void TestCategoriesTest()
        {
            // TODO unit test for the property 'TestCategories'
        }
        /// <summary>
        /// Test the property 'TestCategoriesMatrix'
        /// </summary>
        [Test]
        public void TestCategoriesMatrixTest()
        {
            // TODO unit test for the property 'TestCategoriesMatrix'
        }
        /// <summary>
        /// Test the property 'TestScripts'
        /// </summary>
        [Test]
        public void TestScriptsTest()
        {
            // TODO unit test for the property 'TestScripts'
        }
        /// <summary>
        /// Test the property 'BeforeTestScripts'
        /// </summary>
        [Test]
        public void BeforeTestScriptsTest()
        {
            // TODO unit test for the property 'BeforeTestScripts'
        }
        /// <summary>
        /// Test the property 'AfterTestScripts'
        /// </summary>
        [Test]
        public void AfterTestScriptsTest()
        {
            // TODO unit test for the property 'AfterTestScripts'
        }
        /// <summary>
        /// Test the property 'DeployMode'
        /// </summary>
        [Test]
        public void DeployModeTest()
        {
            // TODO unit test for the property 'DeployMode'
        }
        /// <summary>
        /// Test the property 'Deployments'
        /// </summary>
        [Test]
        public void DeploymentsTest()
        {
            // TODO unit test for the property 'Deployments'
        }
        /// <summary>
        /// Test the property 'DeployScripts'
        /// </summary>
        [Test]
        public void DeployScriptsTest()
        {
            // TODO unit test for the property 'DeployScripts'
        }
        /// <summary>
        /// Test the property 'BeforeDeployScripts'
        /// </summary>
        [Test]
        public void BeforeDeployScriptsTest()
        {
            // TODO unit test for the property 'BeforeDeployScripts'
        }
        /// <summary>
        /// Test the property 'AfterDeployScripts'
        /// </summary>
        [Test]
        public void AfterDeployScriptsTest()
        {
            // TODO unit test for the property 'AfterDeployScripts'
        }
        /// <summary>
        /// Test the property 'XamarinRegisterAndroidProduct'
        /// </summary>
        [Test]
        public void XamarinRegisterAndroidProductTest()
        {
            // TODO unit test for the property 'XamarinRegisterAndroidProduct'
        }
        /// <summary>
        /// Test the property 'XamarinRegisterIosProduct'
        /// </summary>
        [Test]
        public void XamarinRegisterIosProductTest()
        {
            // TODO unit test for the property 'XamarinRegisterIosProduct'
        }
        /// <summary>
        /// Test the property 'MatrixFastFinish'
        /// </summary>
        [Test]
        public void MatrixFastFinishTest()
        {
            // TODO unit test for the property 'MatrixFastFinish'
        }
        /// <summary>
        /// Test the property 'MatrixAllowFailures'
        /// </summary>
        [Test]
        public void MatrixAllowFailuresTest()
        {
            // TODO unit test for the property 'MatrixAllowFailures'
        }
        /// <summary>
        /// Test the property 'MatrixExclude'
        /// </summary>
        [Test]
        public void MatrixExcludeTest()
        {
            // TODO unit test for the property 'MatrixExclude'
        }
        /// <summary>
        /// Test the property 'Artifacts'
        /// </summary>
        [Test]
        public void ArtifactsTest()
        {
            // TODO unit test for the property 'Artifacts'
        }
        /// <summary>
        /// Test the property 'Notifications'
        /// </summary>
        [Test]
        public void NotificationsTest()
        {
            // TODO unit test for the property 'Notifications'
        }

    }

}
