version: 0.1.{build}
image: Visual Studio 2017 Preview
before_build:
- cmd: "dir\ntools\\nuget \ntools\\nuget source add -source https://api.nuget.org/v3/index.json -name v3\ntools\\nuget restore"
build_script:
- ps: >-
    .nuget\nuget.exe

    .nuget\nuget.exe restore

    dotnet build /p:Version=$Env:APPVEYOR_BUILD_VERSION
artifacts:
- path: src\Itofinity.Appveyor.Rest.Refit\bin\Debug\*.nupkg
  name: Package
deploy:
- provider: NuGet
  api_key:
    secure: qTIvhxyMmoK96PQjCdn6o1hzwsc9vivjNpmbQ9s/xnqpKrnQVAxRTa0gK5VQ3yGs
  artifact: Package