version: 0.1.{build}
image: Visual Studio 2017 Preview
before_build:
- ps: >-
    nuget source add -source https://api.nuget.org/v3/index.json -name v3

    nuget.exe restore
build_script:
- ps: >-
    dotnet build /p:Version=$Env:APPVEYOR_BUILD_VERSION
test: off 
artifacts:
- path: src\Itofinity.Appveyor.Rest.Refit\bin\Debug\*.nupkg
  name: Package
#deploy:
#- provider: NuGet
#  api_key:
#    secure: hY+E4XoUEiT4sVDAe2kTy/51qMZsD0jQcoiqUgI9M47/pw0ZCJL06hLMgQh1Guuv
#  artifact: Package
#  on:
#    branch: master
#    appveyor_repo_tag: true
deploy:
- provider: GitHub
  release: Itofinity.Appveyor.Rest.Refit-v$(appveyor_build_version)
  description: 'Itofinity.Appveyor.Rest.Refit Release'
  auth_token:
    secure: T/du7cromXAzDxL+UmsuAgPBZLXUGCeEFauhkUzpM5XZN+NdZuaCqGSYf5PcdXpp # your encrypted token from GitHub
  artifact: /Itofinity\.Appveyor\.Rest\.Refit.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true   