version: 0.1.{build}
image: Visual Studio 2017 Preview
before_build:
- ps: >-
    .nuget\nuget source add -source https://api.nuget.org/v3/index.json -name v3

    .nuget\nuget.exe

    .nuget\nuget.exe restore
build_script:
- ps: >-
    dotnet build /p:Version=$Env:APPVEYOR_BUILD_VERSION
test: off 
artifacts:
- path: src\Itofinity.Appveyor.Rest.Refit\bin\Debug\*.nupkg
  name: Package
deploy:
- provider: NuGet
  api_key:
    secure: qTIvhxyMmoK96PQjCdn6o1hzwsc9vivjNpmbQ9s/xnqpKrnQVAxRTa0gK5VQ3yGs
  artifact: Package