/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using Refit;

using Itofinity.Appveyor.Rest.Refit.Client;
using Itofinity.Appveyor.Rest.Refit.Api;
using Itofinity.Appveyor.Rest.Refit.Model;

namespace Itofinity.Appveyor.Rest.Refit.Test
{
    /// <summary>
    ///  Class for testing EnvironmentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvironmentApiTests
    {
        private string hostUrl = "";
        private string userAgent = "Itofinity.Appveyor.Rest.Refit.Test.EnvironmentApiTests";

        private IEnvironmentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = RestService.For<IEnvironmentApi>(hostUrl);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvironmentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvironmentApi
            //Assert.IsInstanceOfType(typeof(EnvironmentApi), instance, "instance is a EnvironmentApi");
        }

        
        /// <summary>
        /// Test AddEnvironment
        /// </summary>
        [Test]
        public async void AddEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeploymentEnvironmentAddition body = null;
            //var response = await instance.AddEnvironment(userAgent, body);
            //Assert.IsInstanceOf<DeploymentEnvironmentWithSettings> (response, "response is DeploymentEnvironmentWithSettings");
        }
        
        /// <summary>
        /// Test DeleteEnvironment
        /// </summary>
        [Test]
        public async void DeleteEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? deploymentEnvironmentId = null;
            //instance.DeleteEnvironment(userAgent, deploymentEnvironmentId);
            
        }
        
        /// <summary>
        /// Test GetEnvironmentDeployments
        /// </summary>
        [Test]
        public async void GetEnvironmentDeploymentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? deploymentEnvironmentId = null;
            //var response = await instance.GetEnvironmentDeployments(userAgent, deploymentEnvironmentId);
            //Assert.IsInstanceOf<DeploymentEnvironmentDeploymentsResults> (response, "response is DeploymentEnvironmentDeploymentsResults");
        }
        
        /// <summary>
        /// Test GetEnvironmentSettings
        /// </summary>
        [Test]
        public async void GetEnvironmentSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? deploymentEnvironmentId = null;
            //var response = await instance.GetEnvironmentSettings(userAgent, deploymentEnvironmentId);
            //Assert.IsInstanceOf<DeploymentEnvironmentSettingsResults> (response, "response is DeploymentEnvironmentSettingsResults");
        }
        
        /// <summary>
        /// Test GetEnvironments
        /// </summary>
        [Test]
        public async void GetEnvironmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = await instance.GetEnvironments(userAgent);
            //Assert.IsInstanceOf<List<DeploymentEnvironmentLookupModel>> (response, "response is List<DeploymentEnvironmentLookupModel>");
        }
        
        /// <summary>
        /// Test UpdateEnvironment
        /// </summary>
        [Test]
        public async void UpdateEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeploymentEnvironmentWithSettings body = null;
            //var response = await instance.UpdateEnvironment(userAgent, body);
            //Assert.IsInstanceOf<DeploymentEnvironmentWithSettings> (response, "response is DeploymentEnvironmentWithSettings");
        }
        
    }

}
