/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Rest.Refit.Model
{
    /// <summary>
    /// BuildWorkerImage
    /// </summary>
    [DataContract]
    public partial class BuildWorkerImage :  IEquatable<BuildWorkerImage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildWorkerImage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BuildWorkerImage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildWorkerImage" /> class.
        /// </summary>
        /// <param name="BuildWorkerImageId">BuildWorkerImageId (required).</param>
        /// <param name="Name">Name (required).</param>
        /// <param name="BuildCloudName">BuildCloudName.</param>
        /// <param name="OsType">OsType.</param>
        public BuildWorkerImage(int? BuildWorkerImageId = default(int?), BuildWorkerImageName Name = default(BuildWorkerImageName), BuildCloudName BuildCloudName = default(BuildCloudName), OSType OsType = default(OSType))
        {
            // to ensure "BuildWorkerImageId" is required (not null)
            if (BuildWorkerImageId == null)
            {
                throw new InvalidDataException("BuildWorkerImageId is a required property for BuildWorkerImage and cannot be null");
            }
            else
            {
                this.BuildWorkerImageId = BuildWorkerImageId;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for BuildWorkerImage and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            this.BuildCloudName = BuildCloudName;
            this.OsType = OsType;
        }
        
        /// <summary>
        /// Gets or Sets BuildWorkerImageId
        /// </summary>
        [DataMember(Name="buildWorkerImageId", EmitDefaultValue=false)]
        public int? BuildWorkerImageId { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public BuildWorkerImageName Name { get; set; }
        /// <summary>
        /// Gets or Sets BuildCloudName
        /// </summary>
        [DataMember(Name="buildCloudName", EmitDefaultValue=false)]
        public BuildCloudName BuildCloudName { get; set; }
        /// <summary>
        /// Gets or Sets OsType
        /// </summary>
        [DataMember(Name="osType", EmitDefaultValue=false)]
        public OSType OsType { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BuildWorkerImage {\n");
            sb.Append("  BuildWorkerImageId: ").Append(BuildWorkerImageId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BuildCloudName: ").Append(BuildCloudName).Append("\n");
            sb.Append("  OsType: ").Append(OsType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BuildWorkerImage);
        }

        /// <summary>
        /// Returns true if BuildWorkerImage instances are equal
        /// </summary>
        /// <param name="other">Instance of BuildWorkerImage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BuildWorkerImage other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BuildWorkerImageId == other.BuildWorkerImageId ||
                    this.BuildWorkerImageId != null &&
                    this.BuildWorkerImageId.Equals(other.BuildWorkerImageId)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.BuildCloudName == other.BuildCloudName ||
                    this.BuildCloudName != null &&
                    this.BuildCloudName.Equals(other.BuildCloudName)
                ) && 
                (
                    this.OsType == other.OsType ||
                    this.OsType != null &&
                    this.OsType.Equals(other.OsType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BuildWorkerImageId != null)
                    hash = hash * 59 + this.BuildWorkerImageId.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.BuildCloudName != null)
                    hash = hash * 59 + this.BuildCloudName.GetHashCode();
                if (this.OsType != null)
                    hash = hash * 59 + this.OsType.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // BuildWorkerImageId (int?) minimum
            if(this.BuildWorkerImageId < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BuildWorkerImageId, must be a value greater than or equal to 0.", new [] { "BuildWorkerImageId" });
            }

            yield break;
        }
    }

}
