/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Rest.Refit.Model
{
    /// <summary>
    /// DeploymentCancellation
    /// </summary>
    [DataContract]
    public partial class DeploymentCancellation :  IEquatable<DeploymentCancellation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentCancellation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeploymentCancellation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentCancellation" /> class.
        /// </summary>
        /// <param name="DeploymentId">DeploymentId (required).</param>
        public DeploymentCancellation(int? DeploymentId = default(int?))
        {
            // to ensure "DeploymentId" is required (not null)
            if (DeploymentId == null)
            {
                throw new InvalidDataException("DeploymentId is a required property for DeploymentCancellation and cannot be null");
            }
            else
            {
                this.DeploymentId = DeploymentId;
            }
        }
        
        /// <summary>
        /// Gets or Sets DeploymentId
        /// </summary>
        [DataMember(Name="deploymentId", EmitDefaultValue=false)]
        public int? DeploymentId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeploymentCancellation {\n");
            sb.Append("  DeploymentId: ").Append(DeploymentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DeploymentCancellation);
        }

        /// <summary>
        /// Returns true if DeploymentCancellation instances are equal
        /// </summary>
        /// <param name="other">Instance of DeploymentCancellation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeploymentCancellation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DeploymentId == other.DeploymentId ||
                    this.DeploymentId != null &&
                    this.DeploymentId.Equals(other.DeploymentId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DeploymentId != null)
                    hash = hash * 59 + this.DeploymentId.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DeploymentId (int?) minimum
            if(this.DeploymentId < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DeploymentId, must be a value greater than or equal to 0.", new [] { "DeploymentId" });
            }

            yield break;
        }
    }

}
