/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Rest.Refit.Model
{
    /// <summary>
    /// Defines DeploymentProviderType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DeploymentProviderType
    {
        
        /// <summary>
        /// Enum Agent for "Agent"
        /// </summary>
        [EnumMember(Value = "Agent")]
        Agent,
        
        /// <summary>
        /// Enum AzureBlob for "AzureBlob"
        /// </summary>
        [EnumMember(Value = "AzureBlob")]
        AzureBlob,
        
        /// <summary>
        /// Enum AzureCS for "AzureCS"
        /// </summary>
        [EnumMember(Value = "AzureCS")]
        AzureCS,
        
        /// <summary>
        /// Enum AzureWebJob for "AzureWebJob"
        /// </summary>
        [EnumMember(Value = "AzureWebJob")]
        AzureWebJob,
        
        /// <summary>
        /// Enum BinTray for "BinTray"
        /// </summary>
        [EnumMember(Value = "BinTray")]
        BinTray,
        
        /// <summary>
        /// Enum FTP for "FTP"
        /// </summary>
        [EnumMember(Value = "FTP")]
        FTP,
        
        /// <summary>
        /// Enum GitHub for "GitHub"
        /// </summary>
        [EnumMember(Value = "GitHub")]
        GitHub,
        
        /// <summary>
        /// Enum NuGet for "NuGet"
        /// </summary>
        [EnumMember(Value = "NuGet")]
        NuGet,
        
        /// <summary>
        /// Enum S3 for "S3"
        /// </summary>
        [EnumMember(Value = "S3")]
        S3,
        
        /// <summary>
        /// Enum SqlDatabase for "SqlDatabase"
        /// </summary>
        [EnumMember(Value = "SqlDatabase")]
        SqlDatabase,
        
        /// <summary>
        /// Enum WebDeploy for "WebDeploy"
        /// </summary>
        [EnumMember(Value = "WebDeploy")]
        WebDeploy,
        
        /// <summary>
        /// Enum Webhook for "Webhook"
        /// </summary>
        [EnumMember(Value = "Webhook")]
        Webhook
    }

}
