/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Rest.Refit.Model
{
    /// <summary>
    /// ProjectSettingsResults
    /// </summary>
    [DataContract]
    public partial class ProjectSettingsResults :  IEquatable<ProjectSettingsResults>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectSettingsResults" /> class.
        /// </summary>
        /// <param name="Project">Project.</param>
        /// <param name="Settings">Settings.</param>
        /// <param name="Images">Images.</param>
        /// <param name="BuildClouds">BuildClouds.</param>
        /// <param name="DefaultImageName">DefaultImageName.</param>
        public ProjectSettingsResults(Project Project = default(Project), ProjectWithConfiguration Settings = default(ProjectWithConfiguration), List<BuildWorkerImage> Images = default(List<BuildWorkerImage>), List<StringValueObject> BuildClouds = default(List<StringValueObject>), string DefaultImageName = default(string))
        {
            this.Project = Project;
            this.Settings = Settings;
            this.Images = Images;
            this.BuildClouds = BuildClouds;
            this.DefaultImageName = DefaultImageName;
        }
        
        /// <summary>
        /// Gets or Sets Project
        /// </summary>
        [DataMember(Name="project", EmitDefaultValue=false)]
        public Project Project { get; set; }
        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [DataMember(Name="settings", EmitDefaultValue=false)]
        public ProjectWithConfiguration Settings { get; set; }
        /// <summary>
        /// Gets or Sets Images
        /// </summary>
        [DataMember(Name="images", EmitDefaultValue=false)]
        public List<BuildWorkerImage> Images { get; set; }
        /// <summary>
        /// Gets or Sets BuildClouds
        /// </summary>
        [DataMember(Name="buildClouds", EmitDefaultValue=false)]
        public List<StringValueObject> BuildClouds { get; set; }
        /// <summary>
        /// Gets or Sets DefaultImageName
        /// </summary>
        [DataMember(Name="defaultImageName", EmitDefaultValue=false)]
        public string DefaultImageName { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjectSettingsResults {\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("  BuildClouds: ").Append(BuildClouds).Append("\n");
            sb.Append("  DefaultImageName: ").Append(DefaultImageName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProjectSettingsResults);
        }

        /// <summary>
        /// Returns true if ProjectSettingsResults instances are equal
        /// </summary>
        /// <param name="other">Instance of ProjectSettingsResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjectSettingsResults other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Project == other.Project ||
                    this.Project != null &&
                    this.Project.Equals(other.Project)
                ) && 
                (
                    this.Settings == other.Settings ||
                    this.Settings != null &&
                    this.Settings.Equals(other.Settings)
                ) && 
                (
                    this.Images == other.Images ||
                    this.Images != null &&
                    this.Images.SequenceEqual(other.Images)
                ) && 
                (
                    this.BuildClouds == other.BuildClouds ||
                    this.BuildClouds != null &&
                    this.BuildClouds.SequenceEqual(other.BuildClouds)
                ) && 
                (
                    this.DefaultImageName == other.DefaultImageName ||
                    this.DefaultImageName != null &&
                    this.DefaultImageName.Equals(other.DefaultImageName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Project != null)
                    hash = hash * 59 + this.Project.GetHashCode();
                if (this.Settings != null)
                    hash = hash * 59 + this.Settings.GetHashCode();
                if (this.Images != null)
                    hash = hash * 59 + this.Images.GetHashCode();
                if (this.BuildClouds != null)
                    hash = hash * 59 + this.BuildClouds.GetHashCode();
                if (this.DefaultImageName != null)
                    hash = hash * 59 + this.DefaultImageName.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
