/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Rest.Refit.Model
{
    /// <summary>
    /// &#x60;repositoryAuthentication&#x60; is only used for git, mercurial, subversion &#x60;repositoryProvider&#x60;.
    /// </summary>
    [DataContract]
    public partial class ProjectAddition :  IEquatable<ProjectAddition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectAddition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectAddition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectAddition" /> class.
        /// </summary>
        /// <param name="RepositoryProvider">RepositoryProvider (required).</param>
        /// <param name="RepositoryName">URL when repositoryProvider is git, mercurial, subversion username/project when repositoryProvider is gitHub (required).</param>
        /// <param name="RepositoryAuthentication">RepositoryAuthentication.</param>
        /// <param name="RepositoryUsername">Required if repositoryAuthentication is credentials.</param>
        /// <param name="RepositoryPassword">Required if repositoryAuthentication is credentials.</param>
        public ProjectAddition(RepositoryProvider RepositoryProvider = default(RepositoryProvider), string RepositoryName = default(string), RepositoryAuthenticationType RepositoryAuthentication = default(RepositoryAuthenticationType), string RepositoryUsername = default(string), string RepositoryPassword = default(string))
        {
            // to ensure "RepositoryProvider" is required (not null)
            if (RepositoryProvider == null)
            {
                throw new InvalidDataException("RepositoryProvider is a required property for ProjectAddition and cannot be null");
            }
            else
            {
                this.RepositoryProvider = RepositoryProvider;
            }
            // to ensure "RepositoryName" is required (not null)
            if (RepositoryName == null)
            {
                throw new InvalidDataException("RepositoryName is a required property for ProjectAddition and cannot be null");
            }
            else
            {
                this.RepositoryName = RepositoryName;
            }
            this.RepositoryAuthentication = RepositoryAuthentication;
            this.RepositoryUsername = RepositoryUsername;
            this.RepositoryPassword = RepositoryPassword;
        }
        
        /// <summary>
        /// Gets or Sets RepositoryProvider
        /// </summary>
        [DataMember(Name="repositoryProvider", EmitDefaultValue=false)]
        public RepositoryProvider RepositoryProvider { get; set; }
        /// <summary>
        /// URL when repositoryProvider is git, mercurial, subversion username/project when repositoryProvider is gitHub
        /// </summary>
        /// <value>URL when repositoryProvider is git, mercurial, subversion username/project when repositoryProvider is gitHub</value>
        [DataMember(Name="repositoryName", EmitDefaultValue=false)]
        public string RepositoryName { get; set; }
        /// <summary>
        /// Gets or Sets RepositoryAuthentication
        /// </summary>
        [DataMember(Name="repositoryAuthentication", EmitDefaultValue=false)]
        public RepositoryAuthenticationType RepositoryAuthentication { get; set; }
        /// <summary>
        /// Required if repositoryAuthentication is credentials
        /// </summary>
        /// <value>Required if repositoryAuthentication is credentials</value>
        [DataMember(Name="repositoryUsername", EmitDefaultValue=false)]
        public string RepositoryUsername { get; set; }
        /// <summary>
        /// Required if repositoryAuthentication is credentials
        /// </summary>
        /// <value>Required if repositoryAuthentication is credentials</value>
        [DataMember(Name="repositoryPassword", EmitDefaultValue=false)]
        public string RepositoryPassword { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjectAddition {\n");
            sb.Append("  RepositoryProvider: ").Append(RepositoryProvider).Append("\n");
            sb.Append("  RepositoryName: ").Append(RepositoryName).Append("\n");
            sb.Append("  RepositoryAuthentication: ").Append(RepositoryAuthentication).Append("\n");
            sb.Append("  RepositoryUsername: ").Append(RepositoryUsername).Append("\n");
            sb.Append("  RepositoryPassword: ").Append(RepositoryPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProjectAddition);
        }

        /// <summary>
        /// Returns true if ProjectAddition instances are equal
        /// </summary>
        /// <param name="other">Instance of ProjectAddition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjectAddition other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RepositoryProvider == other.RepositoryProvider ||
                    this.RepositoryProvider != null &&
                    this.RepositoryProvider.Equals(other.RepositoryProvider)
                ) && 
                (
                    this.RepositoryName == other.RepositoryName ||
                    this.RepositoryName != null &&
                    this.RepositoryName.Equals(other.RepositoryName)
                ) && 
                (
                    this.RepositoryAuthentication == other.RepositoryAuthentication ||
                    this.RepositoryAuthentication != null &&
                    this.RepositoryAuthentication.Equals(other.RepositoryAuthentication)
                ) && 
                (
                    this.RepositoryUsername == other.RepositoryUsername ||
                    this.RepositoryUsername != null &&
                    this.RepositoryUsername.Equals(other.RepositoryUsername)
                ) && 
                (
                    this.RepositoryPassword == other.RepositoryPassword ||
                    this.RepositoryPassword != null &&
                    this.RepositoryPassword.Equals(other.RepositoryPassword)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RepositoryProvider != null)
                    hash = hash * 59 + this.RepositoryProvider.GetHashCode();
                if (this.RepositoryName != null)
                    hash = hash * 59 + this.RepositoryName.GetHashCode();
                if (this.RepositoryAuthentication != null)
                    hash = hash * 59 + this.RepositoryAuthentication.GetHashCode();
                if (this.RepositoryUsername != null)
                    hash = hash * 59 + this.RepositoryUsername.GetHashCode();
                if (this.RepositoryPassword != null)
                    hash = hash * 59 + this.RepositoryPassword.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RepositoryName (string) minLength
            if(this.RepositoryName != null && this.RepositoryName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RepositoryName, length must be greater than 1.", new [] { "RepositoryName" });
            }

            yield break;
        }
    }

}
