/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20170106.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Rest.Refit.Model
{
    /// <summary>
    /// UserAccountSettings
    /// </summary>
    [DataContract]
    public partial class UserAccountSettings :  IEquatable<UserAccountSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserAccountSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserAccountSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserAccountSettings" /> class.
        /// </summary>
        /// <param name="SuccessfulBuildNotification">SuccessfulBuildNotification (required).</param>
        /// <param name="FailedBuildNotification">FailedBuildNotification (required).</param>
        /// <param name="NotifyWhenBuildStatusChangedOnly">Note that this value is &#x60;true&#x60; on user creation, but behaves as &#x60;false&#x60; when not specified on update.  (default to false).</param>
        /// <param name="SuccessfulDeploymentNotification">SuccessfulDeploymentNotification (required).</param>
        /// <param name="FailedDeploymentNotification">FailedDeploymentNotification (required).</param>
        /// <param name="NotifyWhenDeploymentStatusChangedOnly">Note that this value is &#x60;true&#x60; on user creation, but behaves as &#x60;false&#x60; when not specified on update.  (default to false).</param>
        public UserAccountSettings(BuildNotificationFrequency SuccessfulBuildNotification = default(BuildNotificationFrequency), BuildNotificationFrequency FailedBuildNotification = default(BuildNotificationFrequency), bool? NotifyWhenBuildStatusChangedOnly = false, DeploymentNotificationFrequency SuccessfulDeploymentNotification = default(DeploymentNotificationFrequency), DeploymentNotificationFrequency FailedDeploymentNotification = default(DeploymentNotificationFrequency), bool? NotifyWhenDeploymentStatusChangedOnly = false)
        {
            // to ensure "SuccessfulBuildNotification" is required (not null)
            if (SuccessfulBuildNotification == null)
            {
                throw new InvalidDataException("SuccessfulBuildNotification is a required property for UserAccountSettings and cannot be null");
            }
            else
            {
                this.SuccessfulBuildNotification = SuccessfulBuildNotification;
            }
            // to ensure "FailedBuildNotification" is required (not null)
            if (FailedBuildNotification == null)
            {
                throw new InvalidDataException("FailedBuildNotification is a required property for UserAccountSettings and cannot be null");
            }
            else
            {
                this.FailedBuildNotification = FailedBuildNotification;
            }
            // to ensure "SuccessfulDeploymentNotification" is required (not null)
            if (SuccessfulDeploymentNotification == null)
            {
                throw new InvalidDataException("SuccessfulDeploymentNotification is a required property for UserAccountSettings and cannot be null");
            }
            else
            {
                this.SuccessfulDeploymentNotification = SuccessfulDeploymentNotification;
            }
            // to ensure "FailedDeploymentNotification" is required (not null)
            if (FailedDeploymentNotification == null)
            {
                throw new InvalidDataException("FailedDeploymentNotification is a required property for UserAccountSettings and cannot be null");
            }
            else
            {
                this.FailedDeploymentNotification = FailedDeploymentNotification;
            }
            // use default value if no "NotifyWhenBuildStatusChangedOnly" provided
            if (NotifyWhenBuildStatusChangedOnly == null)
            {
                this.NotifyWhenBuildStatusChangedOnly = false;
            }
            else
            {
                this.NotifyWhenBuildStatusChangedOnly = NotifyWhenBuildStatusChangedOnly;
            }
            // use default value if no "NotifyWhenDeploymentStatusChangedOnly" provided
            if (NotifyWhenDeploymentStatusChangedOnly == null)
            {
                this.NotifyWhenDeploymentStatusChangedOnly = false;
            }
            else
            {
                this.NotifyWhenDeploymentStatusChangedOnly = NotifyWhenDeploymentStatusChangedOnly;
            }
        }
        
        /// <summary>
        /// Gets or Sets SuccessfulBuildNotification
        /// </summary>
        [DataMember(Name="successfulBuildNotification", EmitDefaultValue=false)]
        public BuildNotificationFrequency SuccessfulBuildNotification { get; set; }
        /// <summary>
        /// Gets or Sets FailedBuildNotification
        /// </summary>
        [DataMember(Name="failedBuildNotification", EmitDefaultValue=false)]
        public BuildNotificationFrequency FailedBuildNotification { get; set; }
        /// <summary>
        /// Note that this value is &#x60;true&#x60; on user creation, but behaves as &#x60;false&#x60; when not specified on update. 
        /// </summary>
        /// <value>Note that this value is &#x60;true&#x60; on user creation, but behaves as &#x60;false&#x60; when not specified on update. </value>
        [DataMember(Name="notifyWhenBuildStatusChangedOnly", EmitDefaultValue=false)]
        public bool? NotifyWhenBuildStatusChangedOnly { get; set; }
        /// <summary>
        /// Gets or Sets SuccessfulDeploymentNotification
        /// </summary>
        [DataMember(Name="successfulDeploymentNotification", EmitDefaultValue=false)]
        public DeploymentNotificationFrequency SuccessfulDeploymentNotification { get; set; }
        /// <summary>
        /// Gets or Sets FailedDeploymentNotification
        /// </summary>
        [DataMember(Name="failedDeploymentNotification", EmitDefaultValue=false)]
        public DeploymentNotificationFrequency FailedDeploymentNotification { get; set; }
        /// <summary>
        /// Note that this value is &#x60;true&#x60; on user creation, but behaves as &#x60;false&#x60; when not specified on update. 
        /// </summary>
        /// <value>Note that this value is &#x60;true&#x60; on user creation, but behaves as &#x60;false&#x60; when not specified on update. </value>
        [DataMember(Name="notifyWhenDeploymentStatusChangedOnly", EmitDefaultValue=false)]
        public bool? NotifyWhenDeploymentStatusChangedOnly { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserAccountSettings {\n");
            sb.Append("  SuccessfulBuildNotification: ").Append(SuccessfulBuildNotification).Append("\n");
            sb.Append("  FailedBuildNotification: ").Append(FailedBuildNotification).Append("\n");
            sb.Append("  NotifyWhenBuildStatusChangedOnly: ").Append(NotifyWhenBuildStatusChangedOnly).Append("\n");
            sb.Append("  SuccessfulDeploymentNotification: ").Append(SuccessfulDeploymentNotification).Append("\n");
            sb.Append("  FailedDeploymentNotification: ").Append(FailedDeploymentNotification).Append("\n");
            sb.Append("  NotifyWhenDeploymentStatusChangedOnly: ").Append(NotifyWhenDeploymentStatusChangedOnly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UserAccountSettings);
        }

        /// <summary>
        /// Returns true if UserAccountSettings instances are equal
        /// </summary>
        /// <param name="other">Instance of UserAccountSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserAccountSettings other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SuccessfulBuildNotification == other.SuccessfulBuildNotification ||
                    this.SuccessfulBuildNotification != null &&
                    this.SuccessfulBuildNotification.Equals(other.SuccessfulBuildNotification)
                ) && 
                (
                    this.FailedBuildNotification == other.FailedBuildNotification ||
                    this.FailedBuildNotification != null &&
                    this.FailedBuildNotification.Equals(other.FailedBuildNotification)
                ) && 
                (
                    this.NotifyWhenBuildStatusChangedOnly == other.NotifyWhenBuildStatusChangedOnly ||
                    this.NotifyWhenBuildStatusChangedOnly != null &&
                    this.NotifyWhenBuildStatusChangedOnly.Equals(other.NotifyWhenBuildStatusChangedOnly)
                ) && 
                (
                    this.SuccessfulDeploymentNotification == other.SuccessfulDeploymentNotification ||
                    this.SuccessfulDeploymentNotification != null &&
                    this.SuccessfulDeploymentNotification.Equals(other.SuccessfulDeploymentNotification)
                ) && 
                (
                    this.FailedDeploymentNotification == other.FailedDeploymentNotification ||
                    this.FailedDeploymentNotification != null &&
                    this.FailedDeploymentNotification.Equals(other.FailedDeploymentNotification)
                ) && 
                (
                    this.NotifyWhenDeploymentStatusChangedOnly == other.NotifyWhenDeploymentStatusChangedOnly ||
                    this.NotifyWhenDeploymentStatusChangedOnly != null &&
                    this.NotifyWhenDeploymentStatusChangedOnly.Equals(other.NotifyWhenDeploymentStatusChangedOnly)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SuccessfulBuildNotification != null)
                    hash = hash * 59 + this.SuccessfulBuildNotification.GetHashCode();
                if (this.FailedBuildNotification != null)
                    hash = hash * 59 + this.FailedBuildNotification.GetHashCode();
                if (this.NotifyWhenBuildStatusChangedOnly != null)
                    hash = hash * 59 + this.NotifyWhenBuildStatusChangedOnly.GetHashCode();
                if (this.SuccessfulDeploymentNotification != null)
                    hash = hash * 59 + this.SuccessfulDeploymentNotification.GetHashCode();
                if (this.FailedDeploymentNotification != null)
                    hash = hash * 59 + this.FailedDeploymentNotification.GetHashCode();
                if (this.NotifyWhenDeploymentStatusChangedOnly != null)
                    hash = hash * 59 + this.NotifyWhenDeploymentStatusChangedOnly.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
